# Generated by Django 4.1.3 on 2022-12-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
    ]
