# Generated by Django 4.1.3 on 2022-12-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pods',
            new_name='Cat',
        ),
    ]
