# Generated by Django 4.1.3 on 2022-12-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('adress', models.TextField()),
                ('comment', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
